network/api/urls.py
from rest_framework import routers
from network.api import views


router = routers.DefaultRouter()

router.register(r'jobs', views.JobView, base_name='jobs')
router.register(r'data', views.DataView, base_name='data')
router.register(r'settings', views.SettingsView, base_name='settings')

api_urlpatterns = router.urls

network/base/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from network.base import views

base_urlpatterns = ([
    url(r'^$', views.index, name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='base/about.html'), name='about'),
    url(r'^robots\.txt$', views.robots, name='robots'),
    url(r'^settings_site/$', views.settings_site, name='settings_site'),

    # Observations
    url(r'^observations/$', views.ObservationListView.as_view(), name='observations_list'),
    url(r'^observations/(?P<id>[0-9]+)/$', views.observation_view, name='observation_view'),
    url(r'^observations/(?P<id>[0-9]+)/delete/$', views.observation_delete,
        name='observation_delete'),
    url(r'^observations/new/$', views.observation_new, name='observation_new'),
    url(r'^prediction_windows/(?P<sat_id>[\w.@+-]+)/(?P<transmitter>[\w.@+-]+)/'
        '(?P<start_date>.+)/(?P<end_date>.+)/(?P<station_id>[\w.@+-]+)/$',
        views.prediction_windows, name='prediction_windows_filtered'),
    url(r'^prediction_windows/(?P<sat_id>[\w.@+-]+)/(?P<transmitter>[\w.@+-]+)/'
        '(?P<start_date>.+)/(?P<end_date>.+)/$',
        views.prediction_windows, name='prediction_windows'),
    url(r'^data_verify/(?P<id>[0-9]+)/$', views.data_verify, name='data_verify'),
    url(r'^data_mark_bad/(?P<id>[0-9]+)/$', views.data_mark_bad, name='data_mark_bad'),
    url(r'^observations/data/(?P<id>[0-9]+)/$', views.observation_data_view,
        name='observation_data_view'),

    # Stations
    url(r'^stations/$', views.stations_list, name='stations_list'),
    url(r'^stations/(?P<id>[0-9]+)/$', views.station_view, name='station_view'),
    url(r'^stations/(?P<id>[0-9]+)/delete/$', views.station_delete, name='station_delete'),
    url(r'^stations/edit/$', views.station_edit, name='station_edit'),
    url(r'^stations_all/$', views.StationAllView.as_view({'get': 'list'}), name='stations_all'),

    # Satellites
    url(r'^satellites/(?P<id>[0-9]+)/$', views.satellite_view, name='satellite_view'),
    url(r'^satellite_position/(?P<sat_id>[0-9]+)/$', views.satellite_position,
        name='satellite_position'),
], 'base')

network/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

from avatar import urls as avatar_urls
from allauth import urls as allauth_urls

from network.base.urls import base_urlpatterns
from network.users.urls import users_urlpatterns
from network.api.urls import api_urlpatterns

handler404 = 'network.base.views.custom_404'
handler500 = 'network.base.views.custom_500'

urlpatterns = [
    # Base urls
    url(r'^', include(base_urlpatterns)),

    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(users_urlpatterns)),
    url(r'^accounts/', include(allauth_urls)),
    url(r'^avatar/', include(avatar_urls)),

    url(r'^api/', include(api_urlpatterns))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

network/users/urls.py
from django.conf.urls import url

from network.users import views

users_urlpatterns = ([
    url(r'^redirect/$', views.UserRedirectView.as_view(), name='redirect_user'),
    url(r'^update/$', views.UserUpdateView.as_view(), name='update_user'),
    url(r'^(?P<username>[\w.@+-]+)/$', views.view_user, name='view_user'),
], 'users')

network/base/models.py
import os
from datetime import datetime, timedelta
from shortuuidfield import ShortUUIDField

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.timezone import now
from django.conf import settings
from django.utils.html import format_html

from network.users.models import User
from network.base.helpers import get_apikey


RIG_TYPES = ['Radio', 'SDR']
ANTENNA_BANDS = ['HF', 'VHF', 'UHF', 'L', 'S', 'C', 'X', 'KU']
ANTENNA_TYPES = (
    ('dipole', 'Dipole'),
    ('yagi', 'Yagi'),
    ('helical', 'Helical'),
    ('parabolic', 'Parabolic'),
    ('vertical', 'Verical'),
    ('turnstile', 'Turnstile'),
    ('quadrafilar', 'Quadrafilar'),
    ('eggbeater', 'Eggbeater'),
    ('lindenblad', 'Lindenblad'),
)
OBSERVATION_STATUSES = (
    ('unknown', 'Unknown'),
    ('verified', 'Verified'),
    ('data_not_verified', 'Has Data, Not Verified'),
    ('no_data', 'No Data'),
)


class Rig(models.Model):
    name = models.CharField(choices=zip(RIG_TYPES, RIG_TYPES), max_length=10)
    rictld_number = models.PositiveIntegerField(blank=True, null=True)

    def __unicode__(self):
        return '{0}: {1}'.format(self.name, self.rictld_number)


class Mode(models.Model):
    name = models.CharField(max_length=10, unique=True)

    def __unicode__(self):
        return self.name


class Antenna(models.Model):
    """Model for antennas tracked with SatNOGS."""
    frequency = models.PositiveIntegerField()
    frequency_max = models.PositiveIntegerField()
    band = models.CharField(choices=zip(ANTENNA_BANDS, ANTENNA_BANDS),
                            max_length=5)
    antenna_type = models.CharField(choices=ANTENNA_TYPES, max_length=15)

    def __unicode__(self):
        return '{0} - {1} - {2} - {3}'.format(self.band, self.antenna_type,
                                              self.frequency,
                                              self.frequency_max)


class Station(models.Model):
    """Model for SatNOGS ground stations."""
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=45)
    image = models.ImageField(upload_to='ground_stations', blank=True)
    alt = models.PositiveIntegerField(help_text='In meters above ground')
    lat = models.FloatField(validators=[MaxValueValidator(90),
                                        MinValueValidator(-90)])
    lng = models.FloatField(validators=[MaxValueValidator(180),
                                        MinValueValidator(-180)])
    qthlocator = models.CharField(max_length=255, blank=True)
    location = models.CharField(max_length=255, blank=True)
    antenna = models.ManyToManyField(Antenna, blank=True,
                                     help_text=('If you want to add a new Antenna contact '
                                                '<a href="https://community.satnogs.org/" '
                                                'target="_blank">SatNOGS Team</a>'))
    featured_date = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    last_seen = models.DateTimeField(null=True, blank=True)
    horizon = models.PositiveIntegerField(help_text='In degrees above 0', default=10)
    uuid = models.CharField(db_index=True, max_length=100, blank=True)
    rig = models.ForeignKey(Rig, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['-active', '-last_seen']

    def get_image(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return settings.STATION_DEFAULT_IMAGE

    @property
    def online(self):
        try:
            heartbeat = self.last_seen + timedelta(minutes=int(settings.STATION_HEARTBEAT_TIME))
            return self.active and heartbeat > now()
        except:
            return False

    def state(self):
        if self.online:
            return format_html('<span style="color:green">Online</span>')
        else:
            return format_html('<span style="color:red">Offline</span>')

    @property
    def success_rate(self):
        observations = self.data_set.all().count()
        success = self.data_set.exclude(payload='').count()
        if observations:
            return int(100 * (float(success) / float(observations)))
        else:
            return False

    @property
    def apikey(self):
        return get_apikey(user=self.owner)

    def __unicode__(self):
        return "%d - %s" % (self.pk, self.name)


class Satellite(models.Model):
    """Model for SatNOGS satellites."""
    norad_cat_id = models.PositiveIntegerField()
    name = models.CharField(max_length=45)
    names = models.TextField(blank=True)
    image = models.CharField(max_length=100, blank=True, null=True)
    manual_tle = models.BooleanField(default=False)

    class Meta:
        ordering = ['norad_cat_id']

    def get_image(self):
        if self.image:
            return self.image
        else:
            return settings.SATELLITE_DEFAULT_IMAGE

    @property
    def latest_tle(self):
        try:
            latest_tle = Tle.objects.filter(satellite=self).latest('updated')
            return latest_tle
        except Tle.DoesNotExist:
            return False

    @property
    def tle_no(self):
        try:
            line = self.latest_tle.tle1
            return line[65:68]
        except:
            return False

    @property
    def tle_epoch(self):
        try:
            line = self.latest_tle.tle1
            yd, s = line[18:32].split('.')
            epoch = (datetime.strptime(yd, "%y%j") +
                     timedelta(seconds=float("." + s) * 24 * 60 * 60))
            return epoch
        except:
            return False

    @property
    def data_count(self):
        return Data.objects.filter(observation__satellite=self).count()

    @property
    def verified_count(self):
        data = Data.objects.filter(observation__satellite=self)
        return data.filter(vetted_status='verified').count()

    @property
    def empty_count(self):
        data = Data.objects.filter(observation__satellite=self)
        return data.filter(vetted_status='no_data').count()

    @property
    def unknown_count(self):
        data = Data.objects.filter(observation__satellite=self)
        return data.filter(vetted_status='unknown').count()

    @property
    def success_rate(self):
        try:
            return int(100 * (float(self.verified_count) / float(self.data_count)))
        except:
            return 0

    @property
    def empty_rate(self):
        try:
            return int(100 * (float(self.empty_count) / float(self.data_count)))
        except:
            return 0

    @property
    def unknown_rate(self):
        try:
            return int(100 * (float(self.unknown_count) / float(self.data_count)))
        except:
            return 0

    def __unicode__(self):
        return self.name


class Tle(models.Model):
    tle0 = models.CharField(max_length=100, blank=True)
    tle1 = models.CharField(max_length=200, blank=True)
    tle2 = models.CharField(max_length=200, blank=True)
    updated = models.DateTimeField(auto_now=True, blank=True)
    satellite = models.ForeignKey(Satellite, related_name='tles', null=True)

    class Meta:
        ordering = ['tle0']

    def __unicode__(self):
        return self.tle0


class Transmitter(models.Model):
    """Model for antennas transponders."""
    uuid = ShortUUIDField(db_index=True)
    description = models.TextField()
    alive = models.BooleanField(default=True)
    uplink_low = models.PositiveIntegerField(blank=True, null=True)
    uplink_high = models.PositiveIntegerField(blank=True, null=True)
    downlink_low = models.PositiveIntegerField(blank=True, null=True)
    downlink_high = models.PositiveIntegerField(blank=True, null=True)
    mode = models.ForeignKey(Mode, related_name='transmitters', blank=True,
                             null=True, on_delete=models.SET_NULL)
    invert = models.BooleanField(default=False)
    baud = models.FloatField(validators=[MinValueValidator(0)], null=True, blank=True)
    satellite = models.ForeignKey(Satellite, related_name='transmitters', null=True)

    def __unicode__(self):
        return self.description


class Observation(models.Model):
    """Model for SatNOGS observations."""
    satellite = models.ForeignKey(Satellite)
    transmitter = models.ForeignKey(Transmitter, null=True, related_name='observations')
    tle = models.ForeignKey(Tle, null=True)
    author = models.ForeignKey(User)
    start = models.DateTimeField()
    end = models.DateTimeField()

    class Meta:
        ordering = ['-start', '-end']

    @property
    def is_past(self):
        return self.end < now()

    @property
    def is_future(self):
        return self.end > now()

    @property
    def is_deletable_before_start(self):
        deletion = self.start - timedelta(minutes=int(settings.OBSERVATION_MAX_DELETION_RANGE))
        return deletion > now()

    @property
    def is_deletable_after_end(self):
        deletion = self.end + timedelta(minutes=int(settings.OBSERVATION_MIN_DELETION_RANGE))
        return deletion < now()

    # observation has at least 1 payload submitted, no verification taken into account
    @property
    def has_submitted_data(self):
        return self.data_set.exclude(payload='').count()

    # observaton has at least 1 payload that has been verified good
    @property
    def has_verified_data(self):
        return self.data_set.filter(vetted_status='verified').count()

    # observation is vetted to be all bad data
    @property
    def has_no_data(self):
        return self.data_set.filter(
            vetted_status='no_data').count() == self.data_set.count()

    # observation has at least 1 payload left unvetted
    @property
    def has_unvetted_data(self):
        return self.data_set.filter(vetted_status='unknown').count()

network/base/forms.py
from django import forms

from network.base.models import Station


class StationForm(forms.ModelForm):
    class Meta:
        model = Station
        fields = ['name', 'image', 'alt', 'rig', 'uuid',
                  'lat', 'lng', 'qthlocator',
                  'horizon', 'antenna', 'active']
        image = forms.ImageField(required=False)


class SatelliteFilterForm(forms.Form):
    norad = forms.IntegerField()
    start_date = forms.CharField(required=False)
    end_date = forms.CharField(required=False)
    ground_station = forms.IntegerField(required=False)

network/api/views.py
from django.utils.timezone import now
from django.shortcuts import get_object_or_404
from django.http import Http404

from rest_framework import viewsets, mixins
from rest_framework.response import Response

from network.api.perms import StationOwnerCanEditPermission
from network.api import serializers, filters
from network.base.models import Data, Station


class DataView(viewsets.ModelViewSet, mixins.UpdateModelMixin):
    queryset = Data.objects.all()
    serializer_class = serializers.DataSerializer
    filter_class = filters.DataViewFilter
    permission_classes = [
        StationOwnerCanEditPermission
    ]


class JobView(viewsets.ReadOnlyModelViewSet):
    queryset = Data.objects.filter(payload='')
    serializer_class = serializers.JobSerializer
    filter_class = filters.DataViewFilter
    filter_fields = ('ground_station')

    def get_queryset(self):
        queryset = self.queryset.filter(start__gte=now())
        gs_id = self.request.query_params.get('ground_station', None)
        if gs_id and self.request.user.is_authenticated():
            gs = get_object_or_404(Station, id=gs_id)
            if gs.owner == self.request.user:
                gs.last_seen = now()
                gs.save()
        return queryset


class SettingsView(viewsets.ReadOnlyModelViewSet):
    queryset = Station.objects.all()
    lookup_field = 'uuid'

    def list(self, request):
        raise Http404()

    def retrieve(self, request, queryset=queryset, uuid=None):
        station = get_object_or_404(queryset, uuid=uuid)
        serializer = serializers.SettingsSerializer(station)
        return Response(serializer.data)

network/users/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from braces.views import LoginRequiredMixin

from rest_framework.authtoken.models import Token

from network.users.forms import UserForm
from network.users.models import User
from network.base.forms import StationForm
from network.base.models import Station, Observation, Antenna, Rig


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:view_user",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    form_class = UserForm

    model = User

    def get_success_url(self):
        return reverse("users:view_user",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


def view_user(request, username):
    """View for user page."""
    user = User.objects.get(username=username)
    observations = Observation.objects.filter(author=user)[0:10]
    stations = Station.objects.filter(owner=user)
    try:
        token = Token.objects.get(user=user)
    except:
        token = Token.objects.create(user=user)
    form = StationForm()
    antennas = Antenna.objects.all()
    rigs = Rig.objects.all()

    return render(request, 'users/user_detail.html',
                  {'user': user,
                   'observations': observations,
                   'stations': stations,
                   'token': token,
                   'form': form,
                   'antennas': antennas,
                   'rigs': rigs})

network/templates/base/about.html
{% extends "base.html" %}

{% block title %} - About{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      <h1>About</h1>
      SatNOGS Network is a global management interface to facilitate multiple ground station
      operations remotely. An observer is able to take advantage of the full network of
      SatNOGS ground stations around the world.
      It's part of the <a href="https://satnogs.org/" target="_blank">SatNOGS project</a>.
      <h3>Observations</h3>
      The network is open to anyone. Any observer is able to utilize all available Ground Stations
      and communicate with Satellites. All observations results are public
      and all data are distributed freely under the
      <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">Creative Commons Atribution-Share Alike</a> license.
      <h3>Ground Stations</h3>
      Whether you own satellite ground station equipment or you want
      to build one you can head to
      <a href="https://satnogs.org" target="_blank">SatNOGS Project site</a>
      to get up to date documentation and info on how to build a SatNOGS ground station (still under development).
      <h3>Coding</h3>
      Fluent in Python and/or JS? We need you to help with satnogs-network web application. Take a look to our
      <a href="https://github.com/satnogs/satnogs-network/issues" target="_blank">source code</a> or visit
      our <a href="https://github.com/satnogs/satnogs-network/issues" target="_blank">issues tracker</a>
      to start filling bugs, feature requests or code fixes for existing ones.
      Detailed contribution and development documentation is also availble at
      <a href="http://docs.satnogs.org" target="_blank">docs.satnogs.org</a>.
    </div>
  </div>
{% endblock content %}

network/templates/base/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load tags %}

{% block title %} - Home{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'lib/mapbox.js/mapbox.css' %}">
{% endblock css %}

{% block prenav-content %}
  <div id="map" data-mapboxid="{{ mapbox_id }}" data-mapboxtoken="{{ mapbox_token }}" data-stations="{% url 'base:stations_all' %}"></div>
{% endblock prenav-content %}

{% block content %}
  <div class="row" id="call2action">
    {% if not request.user.is_authenticated %}
      <div class="col-md-8 col-md-offset-2 panel panel-default">
        <h3 class="text-center">
          Ground stations swarm control, at your fingertips.
          <button type="button"
                  class="btn btn-primary btn-lg"
                  data-toggle="modal"
                  data-target="#joinModal">
            Join us!
          </button>
        </h3>
      </div>
    {% endif %}
  </div>
  <div class="row">
    {% if featured_station %}
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Featured Ground Station</h3>
          </div>
          <div class="panel-body">
            <div class="text-center">
              <img src="{{ featured_station.get_image }}"
                   class="img-gs-front"
                   alt="{{ featured_station.name }}"
                   title="{{ featured_station.name }}">
              <h3>
                <a href="{% url 'base:station_view' id=featured_station.id %}">
                   {{ featured_station.name }}
                </a>
              </h3>
            </div>
            <div class="caption">
              <div class="gs-front-line">
                <span class="label label-info">Owner</span>
                <span class="gs-front-data">
                  <a href="{% url 'users:view_user' username=featured_station.owner.username %}">
                    {{ featured_station.owner.displayname }}
                  </a>
                </span>
              </div>
              <div class="gs-front-line">
                <span class="label label-info">Coordinates</span>
                <span class="gs-front-data">
                  {{ featured_station.lng|floatformat:2 }}°,
                  {{ featured_station.lat|floatformat:2 }}°
                </span>
              </div>
              <div class="gs-front-line">
                <span class="label label-info">Antennas</span>
                <span class="gs-front-data">
                  {% for antenna in featured_station.antenna.all %}
                    {{antenna.band}} {{ antenna.antenna_type }}{% if forloop.last %}{% else %},{% endif %}
                  {% endfor %}
                </span>
              </div>
              {% if featured_station.success_rate %}
                <div class="gs-front-line">
                  <span class="label label-info">Success Rate</span>
                  <span class="gs-front-data">
                    <div class="progress" title="{{ featured_station.success_rate }}%">
                      <div class="progress-bar progress-bar-success" data-success-rate="{{ featured_station.success_rate }}">
                        <span class="sr-only">{{ featured_station.success_rate }}% Complete (success)</span>
                      </div>
                      <div class="progress-bar progress-bar-danger" data-percentagerest="{{ featured_station.success_rate|percentagerest }}">
                        <span class="sr-only">{{ featured_station.success_rate|percentagerest }}% Complete (danger)</span>
                      </div>
                    </div>
                  </span>
                </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    {% endif %}
    <div class="{% if featured_station %}col-md-8{% else %}col-md-12{% endif %}">
      <ul class="nav nav-tabs" role="tablist">
        <li class="active">
          <a href="#latest" class="toggle" role="tab" data-toggle="tab">Latest Observations</a>
        </li>
        <li>
          <a href="#scheduled" class="toggle" role="tab" data-toggle="tab">Scheduled Observations</a>
        </li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="latest">
          <table class="table table-hover">
            <thead>
              <th>ID</th>
              <th>Satellite</th>
              <th>Frequency</th>
              <th>Encoding</th>
              <th>Timeframe</th>
              <th>Stations</th>
            </thead>
            <tbody>
              {% for observation in latest_observations.all %}
                <tr>
                  <td>
                    <a href="{% url 'base:observation_view' id=observation.id %}">
                      {% if observation.has_verified_data %}
                        <span class="label label-success" title="There is known good data in this observation"
                      {% elif observation.is_future %}
                        <span class="label label-info" title="This observation is in the future"
                      {% elif observation.has_unvetted_data %}
                        <span class="label label-warning" title="There is data that needs vetting in this observation"
                      {% else %}
                        <span class="label label-danger" title="No good data in this observation"
                      {% endif %}>
                      {{ observation.id }}
                      </span>
                    </a>
                  </td>
                  <td>
                    <a href="#" data-toggle="modal" data-target="#SatelliteModal" data-id="{{ observation.satellite.norad_cat_id }}">
                      {{ observation.satellite.name }}
                    </a>
                  </td>
                  <td>{{ observation.transmitter.downlink_low|frq }}</td>
                  <td>{{ observation.transmitter.mode|default:"-" }}</td>
                  <td>
                    <span class="datetime-date">{{ observation.start|date:"Y-m-d" }}</span>
                    <span class="datetime-time">{{ observation.start|date:"H:i:s" }}</span><br>
                    <span class="datetime-date">{{ observation.end|date:"Y-m-d" }}</span>
                    <span class="datetime-time">{{ observation.end|date:"H:i:s" }}</span>
                  </td>
                  <td>
                    {% regroup observation.data_set.all by ground_station as station_list %}
                    {% for station in station_list %}
                      <a href="{% url 'base:station_view' id=station.grouper.id %}">
                        <span class="label label-primary" title="{{ station.grouper.name }}" data-toggle="tooltip">{{ station.grouper.id }}</span>
                      </a>
                    {% endfor %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="tab-pane" id="scheduled">
          <table class="table table-hover">
            <thead>
              <th>ID</th>
              <th>Satellite</th>
              <th>Frequency</th>
              <th>Encoding</th>
              <th>Timeframe</th>
              <th>Stations</th>
            </thead>
            <tbody>
              {% for observation in scheduled_observations.all %}
                <tr>
                  <td>
                    <a href="{% url 'base:observation_view' id=observation.id %}">
                      <span class="label label-info">
                        {{ observation.id }}
                      </span>
                    </a>
                  </td>
                  <td>
                    <a href="#" data-toggle="modal" data-target="#SatelliteModal" data-id="{{ observation.satellite.norad_cat_id }}">
                      {{ observation.satellite.name }}
                    </a>
                  </td>
                  <td>{{ observation.transmitter.downlink_low|frq }}</td>
                  <td>{{ observation.transmitter.mode }}</td>
                  <td>
                    <span class="datetime-date">{{ observation.start|date:"Y-m-d" }}</span>
                    <span class="datetime-time">{{ observation.start|date:"H:i:s" }}</span><br>
                    <span class="datetime-date">{{ observation.end|date:"Y-m-d" }}</span>
                    <span class="datetime-time">{{ observation.end|date:"H:i:s" }}</span>
                  </td>
                  <td>
                    {% regroup observation.data_set.all by ground_station as station_list %}
                    {% for station in station_list %}
                      <a href="{% url 'base:station_view' id=station.grouper.id %}">
                        <span class="label label-primary" title="{{ station.grouper.name }}" data-toggle="tooltip">{{ station.grouper.id }}</span>
                      </a>
                    {% endfor %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>


  <!-- Join Modal -->
  <div class="modal fade" id="joinModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">
            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">Join SatNGOS Network</h4>
        </div>
        <div class="modal-body">
          SatNOGS network is a global management interface to facilitate multiple ground station
          operations remotely. An observer is able to take advantage of the full network of
          SatNOGS ground stations around the world.
          <h3>Observations</h3>
          The network is open to anyone. Any observer is able to utilize all available Ground Stations
          and communicate with Satellites. All observations results are public
          and all data are distributed freely under the
          <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">Creative Commons Atribution-Share Alike</a> license.
          <h3>Ground Stations</h3>
          Whether you own satellite ground station equipment or you want
          to build one you can head to
          <a href="https://satnogs.org" target="_blank">SatNOGS Project site</a>
          to get up to date documentation and info on how to build a SatNOGS ground station (still under development).
          <h3>Coding</h3>
          Fluent in Python and/or JS? We need you to help with satnogs-network web application. Take a look to our
          <a href="https://github.com/satnogs/satnogs-network/issues" target="_blank">source code</a> or visit
          our <a href="https://github.com/satnogs/satnogs-network/issues" target="_blank">issues tracker</a>
          to start filling bugs, feature requests or code fixes for existing ones.
          Detailed contribution and development documentation is also availble at
          <a href="http://docs.satnogs.org" target="_blank">docs.satnogs.org</a>.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  {% include 'includes/satellite.html' %}
{% endblock content %}

{% block javascript %}
  <script src="{% static 'lib/mapbox.js/mapbox.js' %}"></script>
  <script src="{% static 'js/home.js' %}"></script>
  <script src="{% static 'js/satellite.js' %}"></script>
{% endblock %}