network/api/urls.py
from rest_framework import routers
from network.api import views


router = routers.DefaultRouter()

router.register(r'jobs', views.JobView, base_name='jobs')
router.register(r'data', views.DataView, base_name='data')
router.register(r'settings', views.SettingsView, base_name='settings')

api_urlpatterns = router.urls

network/base/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from network.base import views

base_urlpatterns = ([
    url(r'^$', views.index, name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='base/about.html'), name='about'),
    url(r'^robots\.txt$', views.robots, name='robots'),
    url(r'^settings_site/$', views.settings_site, name='settings_site'),

    # Observations
    url(r'^observations/$', views.ObservationListView.as_view(), name='observations_list'),
    url(r'^observations/(?P<id>[0-9]+)/$', views.observation_view, name='observation_view'),
    url(r'^observations/(?P<id>[0-9]+)/delete/$', views.observation_delete,
        name='observation_delete'),
    url(r'^observations/new/$', views.observation_new, name='observation_new'),
    url(r'^prediction_windows/(?P<sat_id>[\w.@+-]+)/(?P<transmitter>[\w.@+-]+)/'
        '(?P<start_date>.+)/(?P<end_date>.+)/(?P<station_id>[\w.@+-]+)/$',
        views.prediction_windows, name='prediction_windows_filtered'),
    url(r'^prediction_windows/(?P<sat_id>[\w.@+-]+)/(?P<transmitter>[\w.@+-]+)/'
        '(?P<start_date>.+)/(?P<end_date>.+)/$',
        views.prediction_windows, name='prediction_windows'),
    url(r'^data_verify/(?P<id>[0-9]+)/$', views.data_verify, name='data_verify'),
    url(r'^data_mark_bad/(?P<id>[0-9]+)/$', views.data_mark_bad, name='data_mark_bad'),
    url(r'^observations/data/(?P<id>[0-9]+)/$', views.observation_data_view,
        name='observation_data_view'),

    # Stations
    url(r'^stations/$', views.stations_list, name='stations_list'),
    url(r'^stations/(?P<id>[0-9]+)/$', views.station_view, name='station_view'),
    url(r'^stations/(?P<id>[0-9]+)/delete/$', views.station_delete, name='station_delete'),
    url(r'^stations/edit/$', views.station_edit, name='station_edit'),
    url(r'^stations_all/$', views.StationAllView.as_view({'get': 'list'}), name='stations_all'),

    # Satellites
    url(r'^satellites/(?P<id>[0-9]+)/$', views.satellite_view, name='satellite_view'),
    url(r'^satellite_position/(?P<sat_id>[0-9]+)/$', views.satellite_position,
        name='satellite_position'),
], 'base')

network/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

from avatar import urls as avatar_urls
from allauth import urls as allauth_urls

from network.base.urls import base_urlpatterns
from network.users.urls import users_urlpatterns
from network.api.urls import api_urlpatterns

handler404 = 'network.base.views.custom_404'
handler500 = 'network.base.views.custom_500'

urlpatterns = [
    # Base urls
    url(r'^', include(base_urlpatterns)),

    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(users_urlpatterns)),
    url(r'^accounts/', include(allauth_urls)),
    url(r'^avatar/', include(avatar_urls)),

    url(r'^api/', include(api_urlpatterns))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

network/users/urls.py
from django.conf.urls import url

from network.users import views

users_urlpatterns = ([
    url(r'^redirect/$', views.UserRedirectView.as_view(), name='redirect_user'),
    url(r'^update/$', views.UserUpdateView.as_view(), name='update_user'),
    url(r'^(?P<username>[\w.@+-]+)/$', views.view_user, name='view_user'),
], 'users')

network/base/models.py
import os
from datetime import datetime, timedelta
from shortuuidfield import ShortUUIDField

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.timezone import now
from django.conf import settings
from django.utils.html import format_html

from network.users.models import User
from network.base.helpers import get_apikey


RIG_TYPES = ['Radio', 'SDR']
ANTENNA_BANDS = ['HF', 'VHF', 'UHF', 'L', 'S', 'C', 'X', 'KU']
ANTENNA_TYPES = (
    ('dipole', 'Dipole'),
    ('yagi', 'Yagi'),
    ('helical', 'Helical'),
    ('parabolic', 'Parabolic'),
    ('vertical', 'Verical'),
    ('turnstile', 'Turnstile'),
    ('quadrafilar', 'Quadrafilar'),
    ('eggbeater', 'Eggbeater'),
    ('lindenblad', 'Lindenblad'),
)
OBSERVATION_STATUSES = (
    ('unknown', 'Unknown'),
    ('verified', 'Verified'),
    ('data_not_verified', 'Has Data, Not Verified'),
    ('no_data', 'No Data'),
)


class Rig(models.Model):
    name = models.CharField(choices=zip(RIG_TYPES, RIG_TYPES), max_length=10)
    rictld_number = models.PositiveIntegerField(blank=True, null=True)

    def __unicode__(self):
        return '{0}: {1}'.format(self.name, self.rictld_number)


class Mode(models.Model):
    name = models.CharField(max_length=10, unique=True)

    def __unicode__(self):
        return self.name


class Antenna(models.Model):
    """Model for antennas tracked with SatNOGS."""
    frequency = models.PositiveIntegerField()
    frequency_max = models.PositiveIntegerField()
    band = models.CharField(choices=zip(ANTENNA_BANDS, ANTENNA_BANDS),
                            max_length=5)
    antenna_type = models.CharField(choices=ANTENNA_TYPES, max_length=15)

    def __unicode__(self):
        return '{0} - {1} - {2} - {3}'.format(self.band, self.antenna_type,
                                              self.frequency,
                                              self.frequency_max)


class Station(models.Model):
    """Model for SatNOGS ground stations."""
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=45)
    image = models.ImageField(upload_to='ground_stations', blank=True)
    alt = models.PositiveIntegerField(help_text='In meters above ground')
    lat = models.FloatField(validators=[MaxValueValidator(90),
                                        MinValueValidator(-90)])
    lng = models.FloatField(validators=[MaxValueValidator(180),
                                        MinValueValidator(-180)])
    qthlocator = models.CharField(max_length=255, blank=True)
    location = models.CharField(max_length=255, blank=True)
    antenna = models.ManyToManyField(Antenna, blank=True,
                                     help_text=('If you want to add a new Antenna contact '
                                                '<a href="https://community.satnogs.org/" '
                                                'target="_blank">SatNOGS Team</a>'))
    featured_date = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    last_seen = models.DateTimeField(null=True, blank=True)
    horizon = models.PositiveIntegerField(help_text='In degrees above 0', default=10)
    uuid = models.CharField(db_index=True, max_length=100, blank=True)
    rig = models.ForeignKey(Rig, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['-active', '-last_seen']

    def get_image(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return settings.STATION_DEFAULT_IMAGE

    @property
    def online(self):
        try:
            heartbeat = self.last_seen + timedelta(minutes=int(settings.STATION_HEARTBEAT_TIME))
            return self.active and heartbeat > now()
        except:
            return False

    def state(self):
        if self.online:
            return format_html('<span style="color:green">Online</span>')
        else:
            return format_html('<span style="color:red">Offline</span>')

    @property
    def success_rate(self):
        observations = self.data_set.all().count()
        success = self.data_set.exclude(payload='').count()
        if observations:
            return int(100 * (float(success) / float(observations)))
        else:
            return False

    @property
    def apikey(self):
        return get_apikey(user=self.owner)

    def __unicode__(self):
        return "%d - %s" % (self.pk, self.name)


class Satellite(models.Model):
    """Model for SatNOGS satellites."""
    norad_cat_id = models.PositiveIntegerField()
    name = models.CharField(max_length=45)
    names = models.TextField(blank=True)
    image = models.CharField(max_length=100, blank=True, null=True)
    manual_tle = models.BooleanField(default=False)

    class Meta:
        ordering = ['norad_cat_id']

    def get_image(self):
        if self.image:
            return self.image
        else:
            return settings.SATELLITE_DEFAULT_IMAGE

    @property
    def latest_tle(self):
        try:
            latest_tle = Tle.objects.filter(satellite=self).latest('updated')
            return latest_tle
        except Tle.DoesNotExist:
            return False

    @property
    def tle_no(self):
        try:
            line = self.latest_tle.tle1
            return line[65:68]
        except:
            return False

    @property
    def tle_epoch(self):
        try:
            line = self.latest_tle.tle1
            yd, s = line[18:32].split('.')
            epoch = (datetime.strptime(yd, "%y%j") +
                     timedelta(seconds=float("." + s) * 24 * 60 * 60))
            return epoch
        except:
            return False

    @property
    def data_count(self):
        return Data.objects.filter(observation__satellite=self).count()

    @property
    def verified_count(self):
        data = Data.objects.filter(observation__satellite=self)
        return data.filter(vetted_status='verified').count()

    @property
    def empty_count(self):
        data = Data.objects.filter(observation__satellite=self)
        return data.filter(vetted_status='no_data').count()

    @property
    def unknown_count(self):
        data = Data.objects.filter(observation__satellite=self)
        return data.filter(vetted_status='unknown').count()

    @property
    def success_rate(self):
        try:
            return int(100 * (float(self.verified_count) / float(self.data_count)))
        except:
            return 0

    @property
    def empty_rate(self):
        try:
            return int(100 * (float(self.empty_count) / float(self.data_count)))
        except:
            return 0

    @property
    def unknown_rate(self):
        try:
            return int(100 * (float(self.unknown_count) / float(self.data_count)))
        except:
            return 0

    def __unicode__(self):
        return self.name


class Tle(models.Model):
    tle0 = models.CharField(max_length=100, blank=True)
    tle1 = models.CharField(max_length=200, blank=True)
    tle2 = models.CharField(max_length=200, blank=True)
    updated = models.DateTimeField(auto_now=True, blank=True)
    satellite = models.ForeignKey(Satellite, related_name='tles', null=True)

    class Meta:
        ordering = ['tle0']

    def __unicode__(self):
        return self.tle0


class Transmitter(models.Model):
    """Model for antennas transponders."""
    uuid = ShortUUIDField(db_index=True)
    description = models.TextField()
    alive = models.BooleanField(default=True)
    uplink_low = models.PositiveIntegerField(blank=True, null=True)
    uplink_high = models.PositiveIntegerField(blank=True, null=True)
    downlink_low = models.PositiveIntegerField(blank=True, null=True)
    downlink_high = models.PositiveIntegerField(blank=True, null=True)
    mode = models.ForeignKey(Mode, related_name='transmitters', blank=True,
                             null=True, on_delete=models.SET_NULL)
    invert = models.BooleanField(default=False)
    baud = models.FloatField(validators=[MinValueValidator(0)], null=True, blank=True)
    satellite = models.ForeignKey(Satellite, related_name='transmitters', null=True)

    def __unicode__(self):
        return self.description


class Observation(models.Model):
    """Model for SatNOGS observations."""
    satellite = models.ForeignKey(Satellite)
    transmitter = models.ForeignKey(Transmitter, null=True, related_name='observations')
    tle = models.ForeignKey(Tle, null=True)
    author = models.ForeignKey(User)
    start = models.DateTimeField()
    end = models.DateTimeField()

    class Meta:
        ordering = ['-start', '-end']

    @property
    def is_past(self):
        return self.end < now()

    @property
    def is_future(self):
        return self.end > now()

    @property
    def is_deletable_before_start(self):
        deletion = self.start - timedelta(minutes=int(settings.OBSERVATION_MAX_DELETION_RANGE))
        return deletion > now()

    @property
    def is_deletable_after_end(self):
        deletion = self.end + timedelta(minutes=int(settings.OBSERVATION_MIN_DELETION_RANGE))
        return deletion < now()

    # observation has at least 1 payload submitted, no verification taken into account
    @property
    def has_submitted_data(self):
        return self.data_set.exclude(payload='').count()

    # observaton has at least 1 payload that has been verified good
    @property
    def has_verified_data(self):
        return self.data_set.filter(vetted_status='verified').count()

    # observation is vetted to be all bad data
    @property
    def has_no_data(self):
        return self.data_set.filter(
            vetted_status='no_data').count() == self.data_set.count()

    # observation has at least 1 payload left unvetted
    @property
    def has_unvetted_data(self):
        return self.data_set.filter(vetted_status='unknown').count()

network/base/forms.py
from django import forms

from network.base.models import Station


class StationForm(forms.ModelForm):
    class Meta:
        model = Station
        fields = ['name', 'image', 'alt', 'rig', 'uuid',
                  'lat', 'lng', 'qthlocator',
                  'horizon', 'antenna', 'active']
        image = forms.ImageField(required=False)


class SatelliteFilterForm(forms.Form):
    norad = forms.IntegerField()
    start_date = forms.CharField(required=False)
    end_date = forms.CharField(required=False)
    ground_station = forms.IntegerField(required=False)

network/api/views.py
from django.utils.timezone import now
from django.shortcuts import get_object_or_404
from django.http import Http404

from rest_framework import viewsets, mixins
from rest_framework.response import Response

from network.api.perms import StationOwnerCanEditPermission
from network.api import serializers, filters
from network.base.models import Data, Station


class DataView(viewsets.ModelViewSet, mixins.UpdateModelMixin):
    queryset = Data.objects.all()
    serializer_class = serializers.DataSerializer
    filter_class = filters.DataViewFilter
    permission_classes = [
        StationOwnerCanEditPermission
    ]


class JobView(viewsets.ReadOnlyModelViewSet):
    queryset = Data.objects.filter(payload='')
    serializer_class = serializers.JobSerializer
    filter_class = filters.DataViewFilter
    filter_fields = ('ground_station')

    def get_queryset(self):
        queryset = self.queryset.filter(start__gte=now())
        gs_id = self.request.query_params.get('ground_station', None)
        if gs_id and self.request.user.is_authenticated():
            gs = get_object_or_404(Station, id=gs_id)
            if gs.owner == self.request.user:
                gs.last_seen = now()
                gs.save()
        return queryset


class SettingsView(viewsets.ReadOnlyModelViewSet):
    queryset = Station.objects.all()
    lookup_field = 'uuid'

    def list(self, request):
        raise Http404()

    def retrieve(self, request, queryset=queryset, uuid=None):
        station = get_object_or_404(queryset, uuid=uuid)
        serializer = serializers.SettingsSerializer(station)
        return Response(serializer.data)

network/users/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from braces.views import LoginRequiredMixin

from rest_framework.authtoken.models import Token

from network.users.forms import UserForm
from network.users.models import User
from network.base.forms import StationForm
from network.base.models import Station, Observation, Antenna, Rig


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:view_user",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    form_class = UserForm

    model = User

    def get_success_url(self):
        return reverse("users:view_user",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


def view_user(request, username):
    """View for user page."""
    user = User.objects.get(username=username)
    observations = Observation.objects.filter(author=user)[0:10]
    stations = Station.objects.filter(owner=user)
    try:
        token = Token.objects.get(user=user)
    except:
        token = Token.objects.create(user=user)
    form = StationForm()
    antennas = Antenna.objects.all()
    rigs = Rig.objects.all()

    return render(request, 'users/user_detail.html',
                  {'user': user,
                   'observations': observations,
                   'stations': stations,
                   'token': token,
                   'form': form,
                   'antennas': antennas,
                   'rigs': rigs})

network/templates/includes/analytics.html
{% load staticfiles %}

<script src="{% static 'lib/dnt-helper/js/dnt-helper.js' %}"></script>
<script src="{% static 'js/ga.js' %}"></script>

network/templates/includes/satellite.html
<div class="modal fade" id="SatelliteModal" tabindex="-1" role="dialog" aria-labelledby="SatelliteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="SatelliteModalTitle"></h4>
      </div>
        <div class="modal-body">
          <div class="row panel-body">
            <div class="col-md-4 panel-satellite">
              <div>
                <img class="satellite-img-full">
              </div>
            </div>
            <div class="col-md-8">
              <div class="satellite-info">
                <span class="satellite-title"></span>
                <span class="satellite-names"></span>
              </div>
              <div class="satellite-info">
                <span class="label label-default">NORAD ID</span>
                <span class="satellite-id"></span>
              </div>
              <div class="satellite-info">
                <ul class="list-unstyled">
                  <li>
                    <span class="satellite-success"></span>
                  </li>
                  <li>
                    <span class="label label-success satellite-verified" data-toggle="tooltip" data-placement="bottom" title="Successful observations"></span>
                    <span class="label label-warning satellite-unknown" data-toggle="tooltip" data-placement="bottom" title="Unknown observations"></span>
                    <span class="label label-danger satellite-empty" data-toggle="tooltip" data-placement="bottom" title="Empty observations"></span>
                  </li>
                </ul>
              </div>
              <div class="satellite-info">
                <ul class="list-unstyled">
                  <li>
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    <a href="/observations/new/" id="new-obs-link">Schedule new Observation</a>
                  </li>
                  <li>
                    <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
                    <a href="/observations/" id="old-obs-link">Past Observations</a>
                  </li>
                  <li>&nbsp;</li>
                  <li>
                    <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span>
                    <a href="https://db.satnogs.org/" target="_blank" id="db-link">SatNOGS DB Entry & Data</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </form>
    </div>
  </div>
</div>

network/templates/includes/stage_notice.html
{% load staticfiles %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/stage.css' %}">
{% endblock %}

<div class="stage-notice">
  This is the stage enviroment.
  Feel free to test it and <a href="https://github.com/satnogs/satnogs-network/issues" target="_blank">report bugs</a>.
  Production deployment is at <a href="https://network.satnogs.org" target="_blank">network.satnogs.org</a>.
</div>

network/templates/includes/station_edit.html
{% load tags %}

<div class="modal fade" id="StationModal" tabindex="-1" role="dialog" aria-labelledby="StationModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="StationModal">Edit Ground Station</h4>
      </div>
      <form class="form-horizontal"
            role="form"
            enctype="multipart/form-data"
            method="post"
            action="{% url 'base:station_edit' %}">{% csrf_token %}
        <div class="modal-body">
          <div class="form-group">
            <label for="name" class="col-sm-2 control-label">Name</label>
            <div class="col-sm-10">
              <input value="{{ form.name.value|default_if_none:"" }}" id="name" type="text" class="form-control" name="name" placeholder="Name" required>
            </div>
          </div>
          <div class="form-group">
            <label for="image" class="col-sm-2 control-label">Image</label>
            <div class="col-sm-10">
              <input id="image" type="file" name="image">
              {% if form.image.value %}
                <img src="{{ MEDIA_URL }}{{ form.image.value }}"
                     class="station-edit-image">
              {% endif %}
            </div>
          </div>
          <div class="form-group">
            <label for="alt" class="col-sm-2 control-label">Altitude</label>
            <div class="col-sm-10">
              <input value="{{ form.alt.value|default_if_none:"" }}" id="alt" type="number" class="form-control" name="alt" placeholder="Altitude" required>
              <span class="help-block">{{ form.alt.help_text }}</span>
            </div>
          </div>
          <div class="form-group">
            <label for="lat" class="col-sm-2 control-label">Latitude</label>
            <div class="col-sm-10">
              <input value="{{ form.lat.value|default_if_none:"" }}" id="lat" type="text" class="form-control" name="lat" placeholder="Latitude" required>
            </div>
          </div>
          <div class="form-group">
            <label for="lng" class="col-sm-2 control-label">Longtitude</label>
            <div class="col-sm-10">
              <input value="{{ form.lng.value|default_if_none:"" }}" id="lng" type="text" class="form-control" name="lng" placeholder="Longtitude" required">
            </div>
          </div>
          <div class="form-group">
            <label for="qthlocator" class="col-sm-2 control-label">QTH Locator</label>
            <div class="col-sm-10">
              <input class="form-control"
                     id="qthlocator"
                     type="text"
                     name="qthlocator"
                     value="{{ form.qthlocator.value|default_if_none:"Geocoded gridsquare" }}"
                     readonly>
            </div>
          </div>
          <div class="form-group">
            <label for="horizon" class="col-sm-2 control-label">Minimum Horizon</label>
            <div class="col-sm-10">
              <input value="{{ form.horizon.value }}" id="horizon" type="number" class="form-control" name="horizon" placeholder="Minimum horizon for passes, default 10">
              <span class="help-block">{{ form.horizon.help_text }}</span>
            </div>
          </div>
          <div class="form-group">
            <label for="antennas" class="col-sm-2 control-label">Antennas</label>
            <div class="col-sm-10">
              <select multiple class="form-control" name="antenna">
                {% for antenna in antennas %}
                  <option value="{{ antenna.id }}">
                    {{ antenna.band}} {{ antenna.get_antenna_type_display }} | {{ antenna.frequency|frq }} - {{ antenna.frequency_max|frq }}
                  </option>
                {% endfor %}
              </select>
              <span class="help-block">{{ form.antenna.help_text|safe }}</span>
            </div>
          </div>
          <div class="form-group">
            <label for="rig" class="col-sm-2 control-label">Rig</label>
            <div class="col-sm-10">
              <select class="form-control" name="rig">
                <option value="" selected>---</option>
                {% for rig in rigs %}
                  <option value="{{ rig.id }}" {% ifequal station.rig rig %}selected{% endifequal %}>
                    {{ rig }}
                  </option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="form-group has-warning">
            <label for="uuid" class="col-sm-2 control-label">UUID</label>
            <div class="col-sm-10">
              <input value="{{ form.uuid.value|default_if_none:"" }}" id="uuid" type="text" class="form-control" name="uuid" placeholder="UUID">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <input type="checkbox" name="active" {% if form.active.value %}checked="True"{% endif %}>
                  Is it operational?
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <input type="hidden" name="id" value="{{ station.id }}">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>

network/templates/includes/utc.html
<div class="modal fade" id="UTCModal" tabindex="-1" role="dialog" aria-labelledby="UTCModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="UTCModalTitle"><span class="glyphicon glyphicon-time" aria-hidden="true"></span></h4>
      </div>
        <div class="modal-body">
          <div class="panel panel-default">
            <div class="panel-heading">UTC</div>
            <div class="panel-body">
              <span id="timezone-utc"></span>
            </div>
          </div>
          <div class="panel panel-default">
            <div class="panel-heading">your local time</div>
            <div class="panel-body">
              <span id="timezone-local"></span>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </form>
    </div>
  </div>
</div>